"""adding price to listingOccupancy table

Revision ID: 7e44ae985f8f
Revises: 
Create Date: 2022-04-02 13:52:31.468844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e44ae985f8f'
down_revision = '049d28a6594f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_occupancy', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_occupancy', 'price')
    # ### end Alembic commands ###